site_name: haqrae

site_url: https://haqrae.github.io/

nav:
    - home: index.md
    - preamble: preamble.md
    - article 1: article 1.md
    - article 2: article 2.md
    - article 3: article 3.md
    - article 4: article 4.md
    - article 5: article 5.md
    - article 6: article 6.md
    - article 7: article 7.md
    - article 8: article 8.md
    - article 9: article 9.md
    - article 10: article 10.md
    - article 11: article 11.md
    - article 12: article 12.md
    - about: about.md

theme:
    name: material
    palette: purple
