site_name: haqrae

site_url: https://haqrae.github.io/

nav:
  - home: index.md
  - preamble: preamble.md
  - article 1: article 1.md
  - article 2: article 2.md
  - article 3: article 3.md
  - article 4: article 4.md
  - article 5: article 5.md
  - article 6: article 6.md
  - article 7: article 7.md
  - article 8: article 8.md
  - article 9: article 9.md
  - article 10: article 10.md
  - article 11: article 11.md
  - article 12: article 12.md
  - about: about.md

theme:
  name: material
#  icon:
#    logo: material/home
  logo: assets/logo.svg

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.footer

# Additional CSS
extra_css:
  - stylesheets/extra.css
#    features:
#      - header.autohide



#extra:
#  social:
#    - icon: fontawesome/brands/mastodon
#      link: https://fosstodon.org/@squidfunk
extra:

  version:
    provider: haqrae
  generator: false

  social:
    - icon: simple/youtube
      link: http://www.youtube.com/@haqrae

    - icon: simple/whatsapp
      link: https://haqrae.github.io

    - icon: simple/tiktok
      link: https://haqrae.github.io

    - icon: simple/instagram
      link: https://haqrae.github.io

    - icon: simple/github
      link: https://haqrae.github.io


copyright: Copyright &copy; 2020 - 2023 haqrae
